### PR TITLE
chore: Add `values.schema.json` to `apecloud-mysql`

### PR DESCRIPTION
**Pull request by spencercjh**
RESOLVE https://github.com/apecloud/kubeblocks/issues/5767

### CODE REVIEW

**Comment by spencercjh** [comment]
Copied from https://github.com/apecloud/kubeblocks/pull/5774

**Review by ldming — APPROVED** [review]

**Comment by ldming** [comment]
> I've written some internal closed-source helm charts before, but this is my first time writing `values.schema.json` files. What are the best practices for this kind of file? Writing json schema is a pain, you know.

Yes, but at the moment, I haven't found any particularly useful tools for generating schemas.

**Review by ldming — APPROVED** [review]

**Comment by spencercjh** [comment]
> > I've written some internal closed-source helm charts before, but this is my first time writing `values.schema.json` files. What are the best practices for this kind of file? Writing json schema is a pain, you know.
> 
> Yes, but at the moment, I haven't found any particularly useful tools for generating schemas.

Thanks for your review and reply.

**Comment by ldming** [comment]
> > > I've written some internal closed-source helm charts before, but this is my first time writing `values.schema.json` files. What are the best practices for this kind of file? Writing json schema is a pain, you know.
> > 
> > 
> > Yes, but at the moment, I haven't found any particularly useful tools for generating schemas.
> 
> Thanks for your review and reply.

Thank you for your interest in our project and for contributing your code.

**Pull request merged**
