### PR TITLE
feat: addons for halo

### PR DESCRIPTION
**Pull request by binbin21avery**
- fix: #162

添加Halo 数据库的addons ，然后有个问题在 validate configmap,最后报错 
报错误是： failed to validate configmap: [missing ',' in struct literal: 1127:29 expected '}', found 'EOF': 1133:2]

我是在office-postgresql这个文件的基础上进行的修改，不知道为什么创建集群的时候就一直卡在这里，能帮忙给看一下吗

### CODE REVIEW

**Comment by wangyelei** [comment]
Can you provide more detailed information an error occurs during HEML installation or when creating a cluster through kb？

**Comment by shanshanying** [comment]
1. types and values are inconsistent in cue file
a boolean parameter cannot accpet 'on' and 'off' 
image


3. volumeMount paths  cannot be duplicated
volume 'data' and 'halo-config' are mounted to the same path '/data/halo' 
image

5. update image

**Comment by binbin21avery** [comment]
> Contributor

thank you very much

**Comment by binbin21avery** [comment]
> 1. types and values are inconsistent in cue file
>    a boolean parameter cannot accpet 'on' and 'off'
> 
> image
> 3. volumeMount paths  cannot be duplicated
>    volume 'data' and 'halo-config' are mounted to the same path '/data/halo'
> 
> image
> 5. update image

thank you very much

**Comment by binbin21avery** [comment]
我每次启动集群的时候，查看pod都会出来这样一句：

**Comment by shanshanying** [comment]
> 我每次启动集群的时候，查看pod都会出来这样一句：0/3 nodes are available: pod has unbound immediate PersistentVolumeClaims. preemption: 0/3 nodes are available: 3 Preemption is not helpful for scheduling.. 是我的集群配置有问题还是我写的配置文件有问题？
> 
> 我用的是minikube, 每个节点的配置是：
> 
> * cpus: 2
> * disk-size: 50G
> * memory: 4G
>   我是按照文档要求配置的，就不知道为什么总会报这个错误出来
> 
> 原文信息： Events: Type Reason Age From Message
> 
> Warning FailedScheduling 3m23s default-scheduler 0/3 nodes are available: pod has unbound immediate PersistentVolumeClaims. preemption: 0/3 nodes are available: 3 Preemption is not helpful for scheduling.. Normal Scheduled 3m21s default-scheduler Successfully assigned default/halo-halo-0 to minikube-m03

Have you checked your local StorageClass, PV, and PVC status? 
Looks like `PVC` cannot be created.

**Pull request closed without merging**
