### PR TITLE
feat: support mogdb standalone & replication

### LINKED ISSUE #172: [Features] Support MogDB Standalone and Replication Mode
Support MogDB Cluster with following features:
- [x] Create Standalone, and Replication (Primary/Secondary) Cluster
- [x] FailOver/SwitchOver
- [ ] Vscale
- [x] Hscale
- [x] Volumeexpand
- [ ] Stop/Start
- [ ] Restart
- [x] Backup/Restore
- [x] Config
- [x] Monitoring

### PR DESCRIPTION
**Pull request by yabinji**
- fix #172

### CODE REVIEW

**Review by shanshanying — APPROVED** [review]

**Review by ldming — APPROVED** [review]
LGTM

**Review by wangyelei — APPROVED** [review]

**Comment by 1aal** [comment]
When i try to `helm install test-mg addons/mogdb-cluster  --set mode=replication` to install a replication cluster, pod CrashLoopBackOff.
image
logs:
```
➜  ~ k logs pods/test-mg-mogdb-1
Defaulted container "mogdb" out of: mogdb, helper
+ MogDB_Role=
+ REPL_CONN_INFO=
+ cat
+ [[ -d /var/lib/mogdb/tmp ]]
++ hostname
+ hostname=test-mg-mogdb-1
+ [[ test-mg-mogdb-1 =~ -([0-9]+)$ ]]
+ ordinal=1
+ [[ 1 -eq 0 ]]
+ MogDB_Role=standby
+ echo 'test-mg-mogdb-1 10.42.0.86'
+ ncat --send-only test-mg-mogdb-0.test-mg-mogdb-headless 6543
++ ping test-mg-mogdb-0.test-mg-mogdb-headless -c 1
++ sed '1{s/[^(]*(//;s/).*//;q}'
+ remote_ip=10.42.0.85
+ '[' -n 26000 ']'
++ expr 26000 + 1
+ ha_port=26001
++ expr 26000 + 2
+ ha_service_port=26002
+ REPL_CONN_INFO='replconninfo1 = '\''localhost=10.42.0.86 localport=26001 localservice=26002 remotehost=10.42.0.85 remoteport=26001 remoteservice=26002'\'''
+ [[ -n replconninfo1 = 'localhost=10.42.0.86 localport=26001 localservice=26002 remotehost=10.42.0.85 remoteport=26001 remoteservice=26002' ]]
+ export REPL_CONN_INFO
+ source /home/omm/.profile
++ '[' -n '5.0.3(1)-release' ']'
++ '[' -f /root/.bashrc ']'
++ . /root/.bashrc
++ '[' -d /root/bin ']'
++ '[' -d /root/.local/bin ']'
++ export GAUSSLOG=/home/omm/pg_log
++ GAUSSLOG=/home/omm/pg_log
++ export GAUSSHOME=/usr/local/mogdb
++ GAUSSHOME=/usr/local/mogdb
++ export PGDATA=/var/lib/mogdb/data
++ PGDATA=/var/lib/mogdb/data
++ export PATH=/usr/local/mogdb/bin:/usr/local/mogdb/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
++ PATH=/usr/local/mogdb/bin:/usr/local/mogdb/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
++ export LD_LIBRARY_PATH=/usr/local/mogdb/lib:/usr/local/mogdb/lib
++ LD_LIBRARY_PATH=/usr/local/mogdb/lib:/usr/local/mogdb/lib
++ export OG_SUBNET=0.0.0.0/0
++ OG_SUBNET=0.0.0.0/0
++ export PGHOST=/var/lib/mogdb/tmp
++ PGHOST=/var/lib/mogdb/tmp
++ export PGPORT=26000
++ PGPORT=26000
+ cp /home/omm/conf/pg_hba.conf /home/omm/conf/postgresql.conf /tmp/
+ chmod 777 /tmp/postgresql.conf /tmp/pg_hba.conf
+ exec bash /kb-scripts/setup.sh -M standby
mogdb DB SERVER_MODE = standby
mogdb DB SERVER_MODE = standby

                        Message: The supplied GS_PASSWORD is meet requirements.

The files belonging to this database system will be owned by user "omm".
This user must also own the server process.

The database cluster will be initialized with locale "C".
The default text search configuration will be set to "english".

fixing permissions on existing directory /var/lib/mogdb/data ... ok
creating subdirectories ... ok
selecting default max_connections ... 100
selecting default shared_buffers ... 32MB
creating configuration files ... ok
Begin init undo subsystem meta.
[INIT UNDO] Init undo subsystem meta successfully.
creating template1 database in /var/lib/mogdb/data/base/1 ... 2024-01-02 09:15:03.024 [unknown] [unknown] localhost 281473560760336 0[0:0#0]  [BACKEND] WARNING:  macAddr is 25128/284843548, sysidentifier is 1646792954/1578923531, randomNum is 1146713611
ok
initializing pg_authid ... ok
setting password ... ok
initializing dependencies ... ok
loading PL/pgSQL server-side language ... ok
creating system views ... ok
creating performance views ... ok
loading system objects' descriptions ... ok
creating collations ... ok
creating conversions ... ok
creating dictionaries ... ok
setting privileges on built-in objects ... ok
initialize global configure for bucketmap length ... ok
creating information schema ... ok
loading foreign-data wrapper for distfs access ... ok
loading foreign-data wrapper for hdfs access ... ok
loading foreign-data wrapper for log access ... ok
loading hstore extension ... ok
loading foreign-data wrapper for MOT access ... ok
loading security plugin ... ok
update system tables ... ok
creating snapshots catalog ... ok
vacuuming database template1 ... ok
copying template1 to template0 ... ok
copying template1 to postgres ... ok
freezing database template0 ... ok
freezing database template1 ... ok
freezing database postgres ... ok

WARNING: enabling "trust" authentication for local connections
You can change this by editing pg_hba.conf or using the option -A, or
--auth-local and --auth-host, the next time you run gs_initdb.

Success. You can now start the database server of single node using:

    mogdb -D /var/lib/mogdb/data --single_node
or
    gs_ctl start -D /var/lib/mogdb/data -Z single_node -l logfile

Successfully replaced /var/lib/mogdb/data/pg_hba.conf with /tmp/pg_hba.conf.
Successfully replaced /var/lib/mogdb/data/postgresql.conf with /tmp/postgresql.conf.
[2024-01-02 09:15:18.230][243][][gs_ctl]: gs_ctl started,datadir is /var/lib/mogdb/data
[2024-01-02 09:15:18.250][243][][gs_ctl]: waiting for server to start...
.0 LOG:  [Alarm Module]can not read GAUSS_WARNING_TYPE env.

0 LOG:  [Alarm Module]Host Name: test-mg-mogdb-1

0 LOG:  [Alarm Module]Host IP: 10.42.0.86

0 LOG:  [Alarm Module]Get ENV GS_CLUSTER_NAME failed!

0 WARNING:  failed to open feature control file, please check whether it exists: FileName=gaussdb.version, Errno=2, Errmessage=No such file or directory.
0 WARNING:  failed to parse feature control file: gaussdb.version.
0 WARNING:  Failed to load the product control file, so gaussdb cannot distinguish product version.
2024-01-02 09:15:18.347 [unknown] [unknown] localhost 281473005580304 0[0:0#0]  0 [BACKEND] LOG:  when starting as multi_standby mode, we couldn't support data replicaton.
gaussdb.state does not exist, and skipt setting since it is optional.2024-01-02 09:15:18.354 [unknown] [unknown] localhost 281473005580304 0[0:0#0]  0 [BACKEND] LOG:  [Alarm Module]can not read GAUSS_WARNING_TYPE env.

2024-01-02 09:15:18.354 [unknown] [unknown] localhost 281473005580304 0[0:0#0]  0 [BACKEND] LOG:  [Alarm Module]Host Name: test-mg-mogdb-1

2024-01-02 09:15:18.354 [unknown] [unknown] localhost 281473005580304 0[0:0#0]  0 [BACKEND] LOG:  [Alarm Module]Host IP: 10.42.0.86

2024-01-02 09:15:18.354 [unknown] [unknown] localhost 281473005580304 0[0:0#0]  0 [BACKEND] LOG:  [Alarm Module]Get ENV GS_CLUSTER_NAME failed!

2024-01-02 09:15:18.357 [unknown] [unknown] localhost 281473005580304 0[0:0#0]  0 [BACKEND] LOG:  loaded library "security_plugin"
2024-01-02 09:15:18.358 [unknown] [unknown] localhost 281473005580304 0[0:0#0]  0 [BACKEND] WARNING:  could not create any HA TCP/IP sockets
2024-01-02 09:15:18.359 [unknown] [unknown] localhost 281473005580304 0[0:0#0]  0 [BACKEND] LOG:  InitNuma numaNodeNum: 1 numa_distribute_mode: none inheritThreadPool: 0.
2024-01-02 09:15:18.359 [unknown] [unknown] localhost 281473005580304 0[0:0#0]  0 [BACKEND] LOG:  reserved memory for backend threads is: 220 MB
2024-01-02 09:15:18.359 [unknown] [unknown] localhost 281473005580304 0[0:0#0]  0 [BACKEND] LOG:  reserved memory for WAL buffers is: 128 MB
2024-01-02 09:15:18.359 [unknown] [unknown] localhost 281473005580304 0[0:0#0]  0 [BACKEND] LOG:  Set max backend reserve memory is: 348 MB, max dynamic memory is: 11027 MB
2024-01-02 09:15:18.359 [unknown] [unknown] localhost 281473005580304 0[0:0#0]  0 [BACKEND] LOG:  shared memory 400 Mbytes, memory context 11375 Mbytes, max process memory 12288 Mbytes
2024-01-02 09:15:18.439 [unknown] [unknown] localhost 281473005580304 0[0:0#0]  0 [CACHE] LOG:  set data cache  size(402653184)
2024-01-02 09:15:18.449 [unknown] [unknown] localhost 281473005580304 0[0:0#0]  0 [CACHE] LOG:  set metadata cache  size(134217728)
2024-01-02 09:15:18.526 [unknown] [unknown] localhost 281473005580304 0[0:0#0]  0 [SEGMENT_PAGE] LOG:  Segment-page constants: DF_MAP_SIZE: 8156, DF_MAP_BIT_CNT: 65248, DF_MAP_GROUP_EXTENTS: 4175872, IPBLOCK_SIZE: 8168, EXTENTS_PER_IPBLOCK: 1021, IPBLOCK_GROUP_SIZE: 4090, BMT_HEADER_LEVEL0_TOTAL_PAGES: 8323072, BktMapEntryNumberPerBlock: 2038, BktMapBlockNumber: 25, BktBitMaxMapCnt: 512
2024-01-02 09:15:18.542 [unknown] [unknown] localhost 281473005580304 0[0:0#0]  0 [BACKEND] LOG:  mogdb: fsync file "/var/lib/mogdb/data/gaussdb.state.temp" success
2024-01-02 09:15:18.542 [unknown] [unknown] localhost 281473005580304 0[0:0#0]  0 [BACKEND] LOG:  create gaussdb state file success: db state(STARTING_STATE), server mode(Standby), connection index(1)
2024-01-02 09:15:18.581 [unknown] [unknown] localhost 281473005580304 0[0:0#0]  0 [BACKEND] LOG:  max_safe_fds = 979, usable_fds = 1000, already_open = 11
2024-01-02 09:15:18.582 [unknown] [unknown] localhost 281473005580304 0[0:0#0]  0 [BACKEND] LOG:  user configure file is not found, it will be created.
2024-01-02 09:15:18.586 [unknown] [unknown] localhost 281473005580304 0[0:0#0]  0 [BACKEND] WARNING:  Cgroup initialization failed: Cgroup is not mounted

[2024-01-02 09:15:19.640][243][][gs_ctl]:  done
[2024-01-02 09:15:19.640][243][][gs_ctl]: server started (/var/lib/mogdb/data)
[2024-01-02 09:15:19.715][294][][gs_ctl]: gs_ctl full build ,datadir is /var/lib/mogdb/data
waiting for server to shut down.... done
server stopped
[2024-01-02 09:15:20.725][294][][gs_ctl]: current workdir is (/).
[2024-01-02 09:15:20.726][294][][gs_ctl]: fopen build pid file "/var/lib/mogdb/data/gs_build.pid" success
[2024-01-02 09:15:20.726][294][][gs_ctl]: fprintf build pid file "/var/lib/mogdb/data/gs_build.pid" success
[2024-01-02 09:15:20.729][294][][gs_ctl]: fsync build pid file "/var/lib/mogdb/data/gs_build.pid" success
[2024-01-02 09:15:20.730][294][][gs_ctl]: set gaussdb state file when full build build:db state(BUILDING_STATE), server mode(STANDBY_MODE), build mode(FULL_BUILD).
[2024-01-02 09:15:20.744][294][gaussdb][gs_ctl]: build try host(10.42.0.85) port(26001) success
[2024-01-02 09:15:20.744][294][gaussdb][gs_ctl]: connect to server success, build started.
[2024-01-02 09:15:20.744][294][gaussdb][gs_ctl]: create build tag file success
[2024-01-02 09:15:20.829][294][gaussdb][gs_ctl]: clear old target dir success
[2024-01-02 09:15:20.829][294][gaussdb][gs_ctl]: create build tag file again success
[2024-01-02 09:15:20.829][294][gaussdb][gs_ctl]: get system identifier success
[2024-01-02 09:15:20.829][294][gaussdb][gs_ctl]: receiving and unpacking files...
[2024-01-02 09:15:20.829][294][gaussdb][gs_ctl]: create backup label success
[2024-01-02 09:15:21.148][294][gaussdb][gs_ctl]: xlog start point: 0/235B5C0
[2024-01-02 09:15:21.148][294][gaussdb][gs_ctl]: begin build tablespace list
[2024-01-02 09:15:21.148][294][gaussdb][gs_ctl]: finish build tablespace list
[2024-01-02 09:15:21.148][294][gaussdb][gs_ctl]: begin get xlog by xlogstream
[2024-01-02 09:15:21.148][294][gaussdb][gs_ctl]: starting background WAL receiver
[2024-01-02 09:15:21.148][294][gaussdb][gs_ctl]: starting walreceiver
[2024-01-02 09:15:21.149][294][gaussdb][gs_ctl]: begin receive tar files
[2024-01-02 09:15:21.149][294][gaussdb][gs_ctl]: receiving and unpacking files...
[2024-01-02 09:15:21.154][294][gaussdb][gs_ctl]: build try host(10.42.0.85) port(26001) success
[2024-01-02 09:15:21.154][294][gaussdb][gs_ctl]: check identify system success
[2024-01-02 09:15:21.154][294][gaussdb][gs_ctl]: send START_REPLICATION 0/2000000 success
[2024-01-02 09:15:21.391][294][gaussdb][gs_ctl]:  Could not receive data from WAL stream, please check network state and configuration, e.g timeout setting:
[2024-01-02 09:15:21.391][294][gaussdb][gs_ctl]: could not read COPY data:
[2024-01-02 09:15:21.391][294][gaussdb][gs_ctl]: full build failed(/var/lib/mogdb/data).
```

**Comment by yabinji** [comment]
> When i try to `helm install test-mg addons/mogdb-cluster --set mode=replication` to install a replication cluster, pod CrashLoopBackOff. image image logs:
> 
> ```
> ➜  ~ k logs pods/test-mg-mogdb-1 mogdb
> + MogDB_Role=
> + REPL_CONN_INFO=
> + cat
> + [[ -d /var/lib/mogdb/tmp ]]
> ++ hostname
> + hostname=test-mg-mogdb-1
> + [[ test-mg-mogdb-1 =~ -([0-9]+)$ ]]
> + ordinal=1
> + [[ 1 -eq 0 ]]
> + MogDB_Role=standby
> + echo 'test-mg-mogdb-1 10.42.0.86'
> + ncat --send-only test-mg-mogdb-0.test-mg-mogdb-headless 6543
> ++ ping test-mg-mogdb-0.test-mg-mogdb-headless -c 1
> ++ sed '1{s/[^(]*(//;s/).*//;q}'
> + remote_ip=10.42.0.85
> + '[' -n 26000 ']'
> ++ expr 26000 + 1
> + ha_port=26001
> ++ expr 26000 + 2
> + ha_service_port=26002
> + REPL_CONN_INFO='replconninfo1 = '\''localhost=10.42.0.86 localport=26001 localservice=26002 remotehost=10.42.0.85 remoteport=26001 remoteservice=26002'\'''
> + [[ -n replconninfo1 = 'localhost=10.42.0.86 localport=26001 localservice=26002 remotehost=10.42.0.85 remoteport=26001 remoteservice=26002' ]]
> + export REPL_CONN_INFO
> + source /home/omm/.profile
> ++ '[' -n '5.0.3(1)-release' ']'
> ++ '[' -f /root/.bashrc ']'
> ++ . /root/.bashrc
> ++ '[' -d /root/bin ']'
> ++ '[' -d /root/.local/bin ']'
> ++ export GAUSSLOG=/home/omm/pg_log
> ++ GAUSSLOG=/home/omm/pg_log
> ++ export GAUSSHOME=/usr/local/mogdb
> ++ GAUSSHOME=/usr/local/mogdb
> ++ export PGDATA=/var/lib/mogdb/data
> ++ PGDATA=/var/lib/mogdb/data
> ++ export PATH=/usr/local/mogdb/bin:/usr/local/mogdb/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
> ++ PATH=/usr/local/mogdb/bin:/usr/local/mogdb/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
> ++ export LD_LIBRARY_PATH=/usr/local/mogdb/lib:/usr/local/mogdb/lib
> ++ LD_LIBRARY_PATH=/usr/local/mogdb/lib:/usr/local/mogdb/lib
> ++ export OG_SUBNET=0.0.0.0/0
> ++ OG_SUBNET=0.0.0.0/0
> ++ export PGHOST=/var/lib/mogdb/tmp
> ++ PGHOST=/var/lib/mogdb/tmp
> ++ export PGPORT=26000
> ++ PGPORT=26000
> + cp /home/omm/conf/pg_hba.conf /home/omm/conf/postgresql.conf /tmp/
> + chmod 777 /tmp/postgresql.conf /tmp/pg_hba.conf
> + exec bash /kb-scripts/setup.sh -M standby
> mogdb DB SERVER_MODE = standby
> mogdb DB SERVER_MODE = standby
> 
>                         Message: The supplied GS_PASSWORD is meet requirements.
> 
> The files belonging to this database system will be owned by user "omm".
> This user must also own the server process.
> 
> The database cluster will be initialized with locale "C".
> The default text search configuration will be set to "english".
> 
> gs_initdb: directory "/var/lib/mogdb/data" exists but is not empty
> If you want to create a new database system, either remove or empty
> the directory "/var/lib/mogdb/data" or run gs_initdb
> with an argument other than "/var/lib/mogdb/data".
> ```

Is the platform ARM or x86 ？My test platfor is x86 and ouput is：

**Comment by 1aal** [comment]
> > When i try to `helm install test-mg addons/mogdb-cluster --set mode=replication` to install a replication cluster, pod CrashLoopBackOff. image image logs:
> > ```
> > ➜  ~ k logs pods/test-mg-mogdb-1 mogdb
> > + MogDB_Role=
> > + REPL_CONN_INFO=
> > + cat
> > + [[ -d /var/lib/mogdb/tmp ]]
> > ++ hostname
> > + hostname=test-mg-mogdb-1
> > + [[ test-mg-mogdb-1 =~ -([0-9]+)$ ]]
> > + ordinal=1
> > + [[ 1 -eq 0 ]]
> > + MogDB_Role=standby
> > + echo 'test-mg-mogdb-1 10.42.0.86'
> > + ncat --send-only test-mg-mogdb-0.test-mg-mogdb-headless 6543
> > ++ ping test-mg-mogdb-0.test-mg-mogdb-headless -c 1
> > ++ sed '1{s/[^(]*(//;s/).*//;q}'
> > + remote_ip=10.42.0.85
> > + '[' -n 26000 ']'
> > ++ expr 26000 + 1
> > + ha_port=26001
> > ++ expr 26000 + 2
> > + ha_service_port=26002
> > + REPL_CONN_INFO='replconninfo1 = '\''localhost=10.42.0.86 localport=26001 localservice=26002 remotehost=10.42.0.85 remoteport=26001 remoteservice=26002'\'''
> > + [[ -n replconninfo1 = 'localhost=10.42.0.86 localport=26001 localservice=26002 remotehost=10.42.0.85 remoteport=26001 remoteservice=26002' ]]
> > + export REPL_CONN_INFO
> > + source /home/omm/.profile
> > ++ '[' -n '5.0.3(1)-release' ']'
> > ++ '[' -f /root/.bashrc ']'
> > ++ . /root/.bashrc
> > ++ '[' -d /root/bin ']'
> > ++ '[' -d /root/.local/bin ']'
> > ++ export GAUSSLOG=/home/omm/pg_log
> > ++ GAUSSLOG=/home/omm/pg_log
> > ++ export GAUSSHOME=/usr/local/mogdb
> > ++ GAUSSHOME=/usr/local/mogdb
> > ++ export PGDATA=/var/lib/mogdb/data
> > ++ PGDATA=/var/lib/mogdb/data
> > ++ export PATH=/usr/local/mogdb/bin:/usr/local/mogdb/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
> > ++ PATH=/usr/local/mogdb/bin:/usr/local/mogdb/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
> > ++ export LD_LIBRARY_PATH=/usr/local/mogdb/lib:/usr/local/mogdb/lib
> > ++ LD_LIBRARY_PATH=/usr/local/mogdb/lib:/usr/local/mogdb/lib
> > ++ export OG_SUBNET=0.0.0.0/0
> > ++ OG_SUBNET=0.0.0.0/0
> > ++ export PGHOST=/var/lib/mogdb/tmp
> > ++ PGHOST=/var/lib/mogdb/tmp
> > ++ export PGPORT=26000
> > ++ PGPORT=26000
> > + cp /home/omm/conf/pg_hba.conf /home/omm/conf/postgresql.conf /tmp/
> > + chmod 777 /tmp/postgresql.conf /tmp/pg_hba.conf
> > + exec bash /kb-scripts/setup.sh -M standby
> > mogdb DB SERVER_MODE = standby
> > mogdb DB SERVER_MODE = standby
> > 
> >                         Message: The supplied GS_PASSWORD is meet requirements.
> > 
> > The files belonging to this database system will be owned by user "omm".
> > This user must also own the server process.
> > 
> > The database cluster will be initialized with locale "C".
> > The default text search configuration will be set to "english".
> > 
> > gs_initdb: directory "/var/lib/mogdb/data" exists but is not empty
> > If you want to create a new database system, either remove or empty
> > the directory "/var/lib/mogdb/data" or run gs_initdb
> > with an argument other than "/var/lib/mogdb/data".
> > ```
> 
> Is the platform ARM or x86 ？My test platfor is x86 and ouput is：

My platform  env is ARM64

**Comment by yabinji** [comment]
> When i try to `helm install test-mg addons/mogdb-cluster --set mode=replication` to install a replication cluster, pod CrashLoopBackOff. image image logs:
> 
> ```
> ➜  ~ k logs pods/test-mg-mogdb-1 mogdb
> + MogDB_Role=
> + REPL_CONN_INFO=
> + cat
> + [[ -d /var/lib/mogdb/tmp ]]
> ++ hostname
> + hostname=test-mg-mogdb-1
> + [[ test-mg-mogdb-1 =~ -([0-9]+)$ ]]
> + ordinal=1
> + [[ 1 -eq 0 ]]
> + MogDB_Role=standby
> + echo 'test-mg-mogdb-1 10.42.0.86'
> + ncat --send-only test-mg-mogdb-0.test-mg-mogdb-headless 6543
> ++ ping test-mg-mogdb-0.test-mg-mogdb-headless -c 1
> ++ sed '1{s/[^(]*(//;s/).*//;q}'
> + remote_ip=10.42.0.85
> + '[' -n 26000 ']'
> ++ expr 26000 + 1
> + ha_port=26001
> ++ expr 26000 + 2
> + ha_service_port=26002
> + REPL_CONN_INFO='replconninfo1 = '\''localhost=10.42.0.86 localport=26001 localservice=26002 remotehost=10.42.0.85 remoteport=26001 remoteservice=26002'\'''
> + [[ -n replconninfo1 = 'localhost=10.42.0.86 localport=26001 localservice=26002 remotehost=10.42.0.85 remoteport=26001 remoteservice=26002' ]]
> + export REPL_CONN_INFO
> + source /home/omm/.profile
> ++ '[' -n '5.0.3(1)-release' ']'
> ++ '[' -f /root/.bashrc ']'
> ++ . /root/.bashrc
> ++ '[' -d /root/bin ']'
> ++ '[' -d /root/.local/bin ']'
> ++ export GAUSSLOG=/home/omm/pg_log
> ++ GAUSSLOG=/home/omm/pg_log
> ++ export GAUSSHOME=/usr/local/mogdb
> ++ GAUSSHOME=/usr/local/mogdb
> ++ export PGDATA=/var/lib/mogdb/data
> ++ PGDATA=/var/lib/mogdb/data
> ++ export PATH=/usr/local/mogdb/bin:/usr/local/mogdb/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
> ++ PATH=/usr/local/mogdb/bin:/usr/local/mogdb/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
> ++ export LD_LIBRARY_PATH=/usr/local/mogdb/lib:/usr/local/mogdb/lib
> ++ LD_LIBRARY_PATH=/usr/local/mogdb/lib:/usr/local/mogdb/lib
> ++ export OG_SUBNET=0.0.0.0/0
> ++ OG_SUBNET=0.0.0.0/0
> ++ export PGHOST=/var/lib/mogdb/tmp
> ++ PGHOST=/var/lib/mogdb/tmp
> ++ export PGPORT=26000
> ++ PGPORT=26000
> + cp /home/omm/conf/pg_hba.conf /home/omm/conf/postgresql.conf /tmp/
> + chmod 777 /tmp/postgresql.conf /tmp/pg_hba.conf
> + exec bash /kb-scripts/setup.sh -M standby
> mogdb DB SERVER_MODE = standby
> mogdb DB SERVER_MODE = standby
> 
>                         Message: The supplied GS_PASSWORD is meet requirements.
> 
> The files belonging to this database system will be owned by user "omm".
> This user must also own the server process.
> 
> The database cluster will be initialized with locale "C".
> The default text search configuration will be set to "english".
> 
> gs_initdb: directory "/var/lib/mogdb/data" exists but is not empty
> If you want to create a new database system, either remove or empty
> the directory "/var/lib/mogdb/data" or run gs_initdb
> with an argument other than "/var/lib/mogdb/data".
> ```

Is the platform ARM or x86 ？My test platfor is x86 and ouput is： 
企业微信截图_1704188512486

>

**Comment by shanshanying** [comment]
> > > When i try to `helm install test-mg addons/mogdb-cluster --set mode=replication` to install a replication cluster, pod CrashLoopBackOff. image image logs:
> > > ```
> > > ➜  ~ k logs pods/test-mg-mogdb-1 mogdb
> > > + MogDB_Role=
> > > + REPL_CONN_INFO=
> > > + cat
> > > + [[ -d /var/lib/mogdb/tmp ]]
> > > ++ hostname
> > > + hostname=test-mg-mogdb-1
> > > + [[ test-mg-mogdb-1 =~ -([0-9]+)$ ]]
> > > + ordinal=1
> > > + [[ 1 -eq 0 ]]
> > > + MogDB_Role=standby
> > > + echo 'test-mg-mogdb-1 10.42.0.86'
> > > + ncat --send-only test-mg-mogdb-0.test-mg-mogdb-headless 6543
> > > ++ ping test-mg-mogdb-0.test-mg-mogdb-headless -c 1
> > > ++ sed '1{s/[^(]*(//;s/).*//;q}'
> > > + remote_ip=10.42.0.85
> > > + '[' -n 26000 ']'
> > > ++ expr 26000 + 1
> > > + ha_port=26001
> > > ++ expr 26000 + 2
> > > + ha_service_port=26002
> > > + REPL_CONN_INFO='replconninfo1 = '\''localhost=10.42.0.86 localport=26001 localservice=26002 remotehost=10.42.0.85 remoteport=26001 remoteservice=26002'\'''
> > > + [[ -n replconninfo1 = 'localhost=10.42.0.86 localport=26001 localservice=26002 remotehost=10.42.0.85 remoteport=26001 remoteservice=26002' ]]
> > > + export REPL_CONN_INFO
> > > + source /home/omm/.profile
> > > ++ '[' -n '5.0.3(1)-release' ']'
> > > ++ '[' -f /root/.bashrc ']'
> > > ++ . /root/.bashrc
> > > ++ '[' -d /root/bin ']'
> > > ++ '[' -d /root/.local/bin ']'
> > > ++ export GAUSSLOG=/home/omm/pg_log
> > > ++ GAUSSLOG=/home/omm/pg_log
> > > ++ export GAUSSHOME=/usr/local/mogdb
> > > ++ GAUSSHOME=/usr/local/mogdb
> > > ++ export PGDATA=/var/lib/mogdb/data
> > > ++ PGDATA=/var/lib/mogdb/data
> > > ++ export PATH=/usr/local/mogdb/bin:/usr/local/mogdb/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
> > > ++ PATH=/usr/local/mogdb/bin:/usr/local/mogdb/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
> > > ++ export LD_LIBRARY_PATH=/usr/local/mogdb/lib:/usr/local/mogdb/lib
> > > ++ LD_LIBRARY_PATH=/usr/local/mogdb/lib:/usr/local/mogdb/lib
> > > ++ export OG_SUBNET=0.0.0.0/0
> > > ++ OG_SUBNET=0.0.0.0/0
> > > ++ export PGHOST=/var/lib/mogdb/tmp
> > > ++ PGHOST=/var/lib/mogdb/tmp
> > > ++ export PGPORT=26000
> > > ++ PGPORT=26000
> > > + cp /home/omm/conf/pg_hba.conf /home/omm/conf/postgresql.conf /tmp/
> > > + chmod 777 /tmp/postgresql.conf /tmp/pg_hba.conf
> > > + exec bash /kb-scripts/setup.sh -M standby
> > > mogdb DB SERVER_MODE = standby
> > > mogdb DB SERVER_MODE = standby
> > > 
> > >                         Message: The supplied GS_PASSWORD is meet requirements.
> > > 
> > > The files belonging to this database system will be owned by user "omm".
> > > This user must also own the server process.
> > > 
> > > The database cluster will be initialized with locale "C".
> > > The default text search configuration will be set to "english".
> > > 
> > > gs_initdb: directory "/var/lib/mogdb/data" exists but is not empty
> > > If you want to create a new database system, either remove or empty
> > > the directory "/var/lib/mogdb/data" or run gs_initdb
> > > with an argument other than "/var/lib/mogdb/data".
> > > ```
> > 
> > 
> > Is the platform ARM or x86 ？My test platfor is x86 and ouput is：
> 
> My platform env is ARM64

I guess the default resource (cpu and memory) are too small to run a MogDB.

**Pull request merged**
